ARG REL_VER
FROM quay.io/fedora/fedora-bootc:${REL_VER} AS builder

ARG REL_VER
COPY build_files/base-rootfs.sh /usr/local/bin/base-rootfs.sh

RUN <<BUILDER
set -xeuo pipefail
dnf -y install dnf5-plugins
dnf -y copr enable @asahi/fedora-remix-branding
dnf -y install asahi-repos

mkdir -p /base-rootfs
dnf -y --installroot=/base-rootfs \
  --use-host-config \
  --releasever="${REL_VER}" \
  --setopt=install_weak_deps=False \
  --nodocs install \
  fedora-repos-archive xfsprogs e2fsprogs dosfstools bootc ostree nss-altfiles \
  systemd-resolved systemd systemd-pam dbus\
  asahi-platform-metapackage-core \
  grub2-efi-aa64 efibootmgr shim bootupd container-selinux coreutils selinux-policy-targeted \
  binutils \
  bluez \
  btrfs-progs \
  cryptsetup \
  dnf5-plugins \
  iwd \
  openssh-clients \
  openssh-server \
  plymouth \
  plymouth-system-theme \
  sudo \
  vim-minimal \
  kernel-16k \
  linux-firmware \
  brcmfmac-firmware \
  cirrus-audio-firmware

/usr/local/bin/base-rootfs.sh /base-rootfs

mkdir -p /base-rootfs/etc/yum.repos.d /base-rootfs/etc/pki/rpm-gpg
cp -a /etc/yum.repos.d/. /base-rootfs/etc/yum.repos.d/
cp -a /etc/pki/rpm-gpg/. /base-rootfs/etc/pki/rpm-gpg/
ls -la /base-rootfs
BUILDER

FROM scratch
COPY --from=builder /base-rootfs/ /

LABEL containers.bootc 1
LABEL ostree.bootable 1

ENV container=oci
STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
