ARG REL_VER

FROM scratch AS ctx

COPY build_files /

FROM quay.io/fedora/fedora-bootc:${REL_VER} AS builder

ARG REL_VER

RUN <<BUILDER
set -xeuo pipefail
dnf -y install dnf5-plugins
dnf -y copr enable @asahi/fedora-remix-branding
dnf -y install asahi-repos

FS_PREFIX=/base-rootfs

mkdir -p "${FS_PREFIX}"
dnf -y --installroot="${FS_PREFIX}" \
  --use-host-config \
  --releasever="${REL_VER}" \
  --setopt=install_weak_deps=False \
  --nodocs install \
    NetworkManager NetworkManager-wifi \
    acl asahi-platform-metapackage-core attr audit \
    bash-color-prompt bash-completion bc bind-utils binutils bluez bluez-tools \
    bootc bootupd brcmfmac-firmware bsdtar btrfs-progs busybox bzip2 \
    cirrus-audio-firmware compsize container-selinux coreutils crontabs cryptsetup \
    dbus distrobox dnf dnf5-plugins dos2unix dosfstools dracut dracut-network dracut-squash \
    e2fsprogs efibootmgr exfatprogs \
    fastfetch fedora-repos-archive fuse-overlayfs \
    git-core grub2-efi-aa64 \
    hostname htop \
    iproute iputils iwd \
    jq just \
    kernel-16k kmscon-freetype kmscon-gl kmscon-pango \
    less linux-firmware lsof \
    ncurses nix nix-daemon nmap-ncat nss-altfiles \
    opensc openssh-clients openssh-server openssl ostree \
    parted plymouth plymouth-system-theme psmisc python-unversioned-command \
    rsync \
    selinux-policy-targeted shim slirp4netns smartmontools socat sudo symlinks systemd systemd-pam systemd-resolved \
    time tpm2-tools tree tzdata \
    unzip upower usbutils \
    vim-minimal \
    wget which whois \
    xfsprogs xxhash \
    zip zram-generator-defaults

mkdir -p "${FS_PREFIX}"/etc/yum.repos.d "${FS_PREFIX}"/etc/pki/rpm-gpg
cp -a /etc/yum.repos.d/. $FS_PREFIX/etc/yum.repos.d/
cp -a /etc/pki/rpm-gpg/. $FS_PREFIX/etc/pki/rpm-gpg/
ls -la "${FS_PREFIX}"
BUILDER

FROM scratch
COPY --from=builder $FS_PREFIX/ /

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    df -h && /ctx/base-rootfs.sh

LABEL containers.bootc 1

ENV container=oci

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
