FROM scratch AS ctx

COPY ../shared/ /shared

FROM docker.io/library/debian:unstable AS base

FROM base AS builder

RUN --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/root --mount=type=tmpfs,dst=/boot \
    apt update -y && \
    apt install -y git curl make build-essential go-md2man libzstd-dev pkgconf dracut libostree-dev ostree

ENV CARGO_HOME=/tmp/rust
ENV RUSTUP_HOME=/tmp/rust
WORKDIR /home/build
RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    curl --proto '=https' --tlsv1.2 -sSf "https://sh.rustup.rs" | sh -s -- --profile minimal -y && \
    sh -c ". ${RUSTUP_HOME}/env ; /ctx/shared/build.sh"

FROM base AS system
COPY --from=builder /output /

RUN --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/root \
    --mount=type=tmpfs,dst=/boot <<EOF
set -xeuo pipefail
apt update -y
apt install -y wget curl

wget https://bananas-archive.debian.net/bananas-archive/bananas-archive-keyring.gpg -O /tmp/bananas-archive-keyring.gpg
wget https://bananas-archive.debian.net/bananas-archive/bananas-unstable.pref -O /tmp/bananas-unstable.pref
wget https://bananas-archive.debian.net/bananas-archive/bananas-unstable.sources -O /tmp/bananas-unstable.source
cp /tmp/bananas-unstable.source /etc/apt/sources.list.d/bananas.sources
cp /tmp/bananas-unstable.pref /etc/apt/preferences.d/bananas.pref
cp /tmp/bananas-archive-keyring.gpg /etc/apt/keyrings/bananas-archive-keyring.gpg

apt update -y
apt install -y \
  btrfs-progs \
  bubblewrap \
  dosfstools \
  e2fsprogs \
  fdisk \
  firmware-linux-free \
  linux-asahi \
  libnss-resolve \
  libnss-myhostname \
  openssh-server \
  skopeo \
  systemd \
  systemd-boot* \
  systemd-resolved \
  xfsprogs \
  libostree-dev
ls /boot
cp /boot/vmlinu* "$(find /usr/lib/modules -maxdepth 1 -type d | tail -n 1)/vmlinuz"
apt clean -y
EOF

RUN systemctl enable systemd-networkd systemd-resolved ssh && \
    printf 'L! /etc/resolv.conf - - - - /run/systemd/resolve/stub-resolv.conf\n' \
        > /usr/lib/tmpfiles.d/resolv-conf.conf && \
    sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config || true

RUN --mount=type=tmpfs,dst=/tmp --mount=type=tmpfs,dst=/root \
    --mount=type=bind,from=ctx,source=/,target=/ctx \
    /ctx/shared/initramfs.sh

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    sed -i 's|^HOME=.*|HOME=/var/home|' "/etc/default/useradd" && \
    /ctx/shared/bootc-rootfs.sh

LABEL containers.bootc 1

RUN bootc container lint
