#!/usr/bin/env bash
# Convert a dnf --installroot tree into a bootc/ostree-style rootfs.

set -Eeuo pipefail
shopt -s nullglob dotglob

usage() {
    printf 'Usage: %s [--skip-chroot] ROOTFS\n' "$0" >&2
}

skip_chroot=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-chroot)
            skip_chroot=1
            shift
            ;;
        --)
            shift
            break
            ;;
        -*|*)
            break
            ;;
    esac
done

if [[ $# -ne 1 ]]; then
    usage
    exit 2
fi

ROOTFS=$(realpath "$1")
[[ -d "$ROOTFS" ]] || { printf 'rootfs is not a directory: %s\n' "$ROOTFS" >&2; exit 1; }

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

remove_path() {
    local path=$1
    [[ "$path" == "$ROOTFS/"* ]] || die "refusing to remove path outside rootfs: $path"
    [[ -e "$path" || -L "$path" ]] || return 0
    rm -rf -- "${path:?}"
}

relocate_dir() {
    local target=$2 source_path="$ROOTFS/$1" target_path="$ROOTFS/$2"
    mkdir -p -- "$target_path"

    if [[ -L "$source_path" ]]; then
        [[ "$(readlink "$source_path")" == "$target" ]] && return
        remove_path "$source_path"
    elif [[ -e "$source_path" ]]; then
        [[ -d "$source_path" ]] || die "$source_path exists but is not a directory"
        remove_path "$source_path"
    fi

    mkdir -p -- "$(dirname "$source_path")"
    ln -s -- "$target" "$source_path"
}

ensure_link() {
    local path=$1 target=$2
    if [[ -L "$path" && "$(readlink "$path")" == "$target" ]]; then
        return
    fi
    remove_path "$path"
    mkdir -p -- "$(dirname "$path")"
    ln -s -- "$target" "$path"
}

printf 'Adjusting top-level layout\n'
relocate_dir home var/home
relocate_dir root var/roothome
relocate_dir opt var/opt
relocate_dir srv var/srv
relocate_dir mnt var/mnt
relocate_dir media run/media
relocate_dir usr/local ../var/usrlocal
mkdir -p -- "$ROOTFS/sysroot"

ensure_link "$ROOTFS/ostree" sysroot/ostree

printf 'Generating /var metadata\n'
mkdir -p -- "$ROOTFS/usr/lib/tmpfiles.d" "$ROOTFS/var"
cat > "$ROOTFS/usr/lib/tmpfiles.d/bootc-base-var.conf" <<'EOF'
# Generated by base-rootfs.sh
d /var/home 0755 root root -
d /var/roothome 0700 root root -
d /var/lib 0755 root root -
d /var/lib/rpm-state 0755 root root -
d /var/opt 0755 root root -
d /var/srv 0755 root root -
d /var/mnt 0755 root root -
d /var/usrlocal 0755 root root -
d /var/usrlocal/bin 0755 root root -
d /var/usrlocal/etc 0755 root root -
d /var/usrlocal/games 0755 root root -
d /var/usrlocal/include 0755 root root -
d /var/usrlocal/lib 0755 root root -
d /var/usrlocal/lib64 0755 root root -
d /var/usrlocal/sbin 0755 root root -
d /var/usrlocal/share 0755 root root -
d /var/usrlocal/src 0755 root root -
d /var/tmp 1777 root root -
EOF
# Preserve additional top-level /var directories created by packages.
for path in "$ROOTFS/var"/*; do
    [[ -d "$path" && ! -L "$path" ]] || continue
    relative=${path#"$ROOTFS/"}
    case "$relative" in
        var/home|var/roothome|var/lib|var/opt|var/srv|var/mnt|var/usrlocal|var/tmp)
            continue
            ;;
    esac
    mode=$(stat -c '%a' "$path")
    printf 'd /%s %s root root -\n' "$relative" "$mode" >> "$ROOTFS/usr/lib/tmpfiles.d/bootc-var-ext.conf"
done
cat >$ROOTFS/usr/lib/tmpfiles.d/bootc-base-rpmstate.conf <<'EOF'
# Workaround for https://bugzilla.redhat.com/show_bug.cgi?id=771713
d /var/lib/rpm-state 0755 - - -
EOF
ensure_link "$ROOTFS/var/run" ../run
remove_path "$ROOTFS/usr/lib/tmpfiles.d/home.conf"

for directory in var/cache var/tmp var/log; do
    [[ -d "$ROOTFS/$directory" ]] && rm -rf -- "${ROOTFS:?}/$directory"/*
done

provision="$ROOTFS/usr/lib/tmpfiles.d/provision.conf"
if [[ -f "$provision" ]]; then
    # Replace only the path field, not comments or arguments containing /root.
    sed -E 's#^([[:space:]]*[^[:space:]]+[[:space:]]+)/root(/[^[:space:]]*)?([[:space:]].*)?$#\1/var/roothome\2\3#' \
        "$provision" > "$provision.tmp"
    mv -- "$provision.tmp" "$provision"
fi

printf 'Writing bootc configuration\n'
mkdir -p -- "$ROOTFS/usr/lib/ostree" "$ROOTFS/usr/lib/kernel/install.conf.d"
cat > "$ROOTFS/usr/lib/ostree/prepare-root.conf" <<'EOF'
[composefs]
enabled = true

[sysroot]
readonly = true
EOF
printf 'layout=ostree\n' > "$ROOTFS/usr/lib/kernel/install.conf"
printf 'layout=ostree\n' > "$ROOTFS/usr/lib/kernel/install.conf.d/00-bootc-kernel-layout.conf"

mkdir -p -- "$ROOTFS/usr/lib/dracut/dracut.conf.d"
cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/10-bootc-base.conf" <<'EOF'
# Generated by base-rootfs.sh
hostonly=no
export DRACUT_NO_XATTR=1
add_dracutmodules+=" kernel-modules dracut-systemd systemd-initrd base ostree bootc "
EOF
cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/59-altfiles.conf" <<'EOF'
# Generated by base-rootfs.sh
install_items+=" /usr/lib/passwd /usr/lib/group "
EOF
cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/22-bootc-generic.conf" <<'EOF'
# Generated by base-rootfs.sh
add_dracutmodules+=" "
EOF
if [[ -d "$ROOTFS/usr/lib/dracut/modules.d/97tpm2-tss" ]]; then
    cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/49-bootc-tpm2-tss.conf" <<'EOF'
# Generated by base-rootfs.sh
add_dracutmodules+=" tpm2-tss "
EOF
fi

if [ -d "$ROOTFS/usr/share/dnf5/libdnf.conf.d/" ]; then
    echo -e "[main]\ninstallonlypkgs=''" >> $ROOTFS/usr/share/dnf5/libdnf.conf.d/20-ostree-installonlypkgs.conf
    echo -e "[main]\nprotect_running_kernel=False" >> $ROOTFS/usr/share/dnf5/libdnf.conf.d/20-ostree-protect_running_kernel.conf
  else
    echo "installonlypkgs=''" >> $ROOTFS/etc/dnf/dnf.conf
    echo "protect_running_kernel=False" >> $ROOTFS/etc/dnf/dnf.conf
fi

if [[ -f "$ROOTFS/etc/passwd" ]]; then
    mkdir -p -- "$ROOTFS/usr/lib"
    cp -a -- "$ROOTFS/etc/passwd" "$ROOTFS/usr/lib/passwd"
fi
if [[ -f "$ROOTFS/etc/group" ]]; then
    mkdir -p -- "$ROOTFS/usr/lib"
    cp -a -- "$ROOTFS/etc/group" "$ROOTFS/usr/lib/group"
fi

mkdir -p -- "$ROOTFS/usr/lib/systemd/system/local-fs.target.wants" "$ROOTFS/usr/lib/systemd/system-preset"
ensure_link "$ROOTFS/usr/lib/systemd/system/local-fs.target.wants/tmp.mount" ../tmp.mount
cat > "$ROOTFS/usr/lib/systemd/system-preset/85-bootc.preset"  <<'EOF'
# Generated by base-rootfs.sh\n'
# Avoid refreshing package metadata on every boot of an immutable image.
disable dnf-makecache.timer
enable bootloader-update.service
EOF
mkdir -p -- "$ROOTFS/etc"
: > "$ROOTFS/etc/machine-id"

run_chroot() {
    chroot "$ROOTFS" "$@"
}

if (( ! skip_chroot )) && [[ -d "$ROOTFS/usr/lib/modules" ]]; then
    (( EUID == 0 )) || die 'chroot operations require root; use --skip-chroot'
    modules=("$ROOTFS/usr/lib/modules"/*)
    kernel_dir=''
    for candidate in "${modules[@]}"; do
        [[ -d "$candidate" ]] && { kernel_dir=$candidate; break; }
    done
    if [[ -n "$kernel_dir" ]]; then
        kver=${kernel_dir##*/}
        root_path="$ROOTFS/root"
        root_was_symlink=0
        if [[ -L "$root_path" ]]; then
            root_was_symlink=1
            remove_path "$root_path"
            mkdir -p -- "$root_path"
        fi
        mounted=()
        cleanup_chroot() {
            for (( i=${#mounted[@]}-1; i>=0; i-- )); do
                umount -R -- "${mounted[i]}" 2>/dev/null || true
            done
            if (( root_was_symlink )); then
                remove_path "$root_path"
                ln -s -- var/roothome "$root_path"
            fi
        }
        trap cleanup_chroot EXIT
        for systemd_dir in etc/systemd/system etc/systemd/user; do
            remove_path "$ROOTFS/$systemd_dir"
            mkdir -p -- "$ROOTFS/$systemd_dir"
        done
        for mountpoint in proc sys dev; do mkdir -p -- "$ROOTFS/$mountpoint"; done
        mount -t proc proc "$ROOTFS/proc"; mounted+=("$ROOTFS/proc")
        mount -t sysfs sys "$ROOTFS/sys"; mounted+=("$ROOTFS/sys")
        mount --rbind /dev "$ROOTFS/dev"; mounted+=("$ROOTFS/dev")
        run_chroot depmod "$kver"
        run_chroot dracut --reproducible -v --no-hostonly --kver "$kver" --force "/usr/lib/modules/$kver/initramfs.img"
        run_chroot systemctl preset-all
        run_chroot systemctl --user --global preset-all
        cleanup_chroot
        trap - EXIT
    fi
fi

bootupd_metadata() {
    local bootupctl="$ROOTFS/usr/bin/bootupctl"
    [[ -x "$bootupctl" ]] || return 0

    local updates="$ROOTFS/usr/lib/bootupd/updates"
    local timestamp
    timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    mkdir -p -- "$updates"

    rpm_evr() {
        (( skip_chroot )) && return 0
        chroot "$ROOTFS" rpm -q --qf '%{EVR}' "$1" 2>/dev/null || true
    }

    local efi_source="$ROOTFS/boot/efi/EFI"
    if [[ -d "$efi_source" ]]; then
        local arch grub_package shim_package grub_version shim_version version_parts versions
        arch=$(uname -m)
        case "$arch" in
            x86_64) grub_package=grub2-efi-x64; shim_package=shim-x64 ;;
            aarch64) grub_package=grub2-efi-aa64; shim_package=shim-aa64 ;;
            *) grub_package=grub2-efi-x64; shim_package=shim-x64 ;;
        esac

        remove_path "$updates/EFI"
        cp -a -- "$efi_source" "$updates/EFI"
        grub_version=$(rpm_evr "$grub_package")
        shim_version=$(rpm_evr "$shim_package")
        version_parts=()
        versions=()
        if [[ -n "$grub_version" ]]; then
            version_parts+=("$grub_package-$grub_version")
            versions+=("{\"name\": \"grub2\", \"rpm_evr\": \"$grub_version\"}")
        fi
        if [[ -n "$shim_version" ]]; then
            version_parts+=("$shim_package-$shim_version")
            versions+=("{\"name\": \"shim\", \"rpm_evr\": \"$shim_version\"}")
        fi
        local version_csv versions_json
        version_csv=$(IFS=,; printf '%s' "${version_parts[*]}")
        versions_json=$(IFS=,; printf '%s' "${versions[*]}")
        printf '{\n  "timestamp": "%s",\n  "version": "%s",\n  "versions": [%s]\n}\n' \
            "$timestamp" "$version_csv" "$versions_json" > "$updates/EFI.json"
    fi
}

printf 'Generating bootupd metadata\n'
bootupd_metadata

printf 'Relocating boot files\n'
mkdir -p -- "$ROOTFS/usr/lib/ostree-boot"
if [[ -d "$ROOTFS/boot" ]]; then
    boot_entries=("$ROOTFS/boot"/*)
    for entry in "${boot_entries[@]}"; do
        [[ -e "$entry" || -L "$entry" ]] || continue
        cp -a -- "$entry" "$ROOTFS/usr/lib/ostree-boot/"
        remove_path "$entry"
    done
fi
mkdir -p -- "$ROOTFS/boot"

mkdir -p -- "$ROOTFS/usr/lib/ostree-boot/loader"

printf 'Cleaning transient files\n'
for directory in var/cache var/tmp var/log run tmp; do
    [[ -d "$ROOTFS/$directory" ]] && rm -rf -- "${ROOTFS:?}/$directory"/*
done
remove_path "$ROOTFS/var/lib/rpm/rpmdb.sqlite-wal"
remove_path "$ROOTFS/var/lib/rpm/rpmdb.sqlite-shm"

printf 'Rootfs finalized: %s\n' "$ROOTFS"
