#!/usr/bin/env bash
# Convert a dnf --installroot tree into a bootc/ostree-style rootfs.

set -Eeuo pipefail
shopt -s nullglob dotglob

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
    printf 'Usage: %s [--skip-chroot] ROOTFS\n' "$0" >&2
}

skip_chroot=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-chroot) skip_chroot=1; shift ;;
        --) shift; break ;;
        *) break ;;
    esac
done

[[ $# -eq 1 ]] || { usage; exit 2; }
ROOTFS=$(realpath "$1")
[[ -d "$ROOTFS" ]] || die "rootfs is not a directory: $ROOTFS"

remove_path() {
    local path=$1
    [[ "$path" == "$ROOTFS/"* ]] || die "refusing to remove path outside rootfs: $path"
    [[ -e "$path" || -L "$path" ]] || return 0
    rm -rf -- "${path:?}"
}

relocate_dir() {
    local target=$2 source_path="$ROOTFS/$1" target_path="$ROOTFS/$2"
    mkdir -p -- "$target_path"
    if [[ -L "$source_path" ]]; then
        [[ "$(readlink "$source_path")" == "$target" ]] && return
        remove_path "$source_path"
    elif [[ -e "$source_path" ]]; then
        [[ -d "$source_path" ]] || die "$source_path exists but is not a directory"
        remove_path "$source_path"
    fi
    mkdir -p -- "$(dirname "$source_path")"
    ln -s -- "$target" "$source_path"
}

ensure_link() {
    local path=$1 target=$2
    if [[ -L "$path" && "$(readlink "$path")" == "$target" ]]; then
        return
    fi
    remove_path "$path"
    mkdir -p -- "$(dirname "$path")"
    ln -s -- "$target" "$path"
}

printf 'Adjusting top-level layout\n'
relocate_dir home var/home
relocate_dir root var/roothome
relocate_dir opt var/opt
relocate_dir srv var/srv
relocate_dir mnt var/mnt
relocate_dir media run/media
relocate_dir usr/local ../var/usrlocal
mkdir -p -- "$ROOTFS/sysroot"
ensure_link "$ROOTFS/ostree" sysroot/ostree

printf 'Generating /var metadata\n'
mkdir -p -- "$ROOTFS/usr/lib/tmpfiles.d" "$ROOTFS/var"
cat > "$ROOTFS/usr/lib/tmpfiles.d/bootc-base-var.conf" <<'EOF'
# Generated by imagectl
d /var/home 0755 root root -
d /var/roothome 0700 root root -
d /var/lib 0755 root root -
d /var/lib/rpm-state 0755 root root -
d /var/opt 0755 root root -
d /var/srv 0755 root root -
d /var/mnt 0755 root root -
d /var/usrlocal 0755 root root -
d /var/usrlocal/bin 0755 root root -
d /var/usrlocal/etc 0755 root root -
d /var/usrlocal/games 0755 root root -
d /var/usrlocal/include 0755 root root -
d /var/usrlocal/lib 0755 root root -
d /var/usrlocal/lib64 0755 root root -
d /var/usrlocal/sbin 0755 root root -
d /var/usrlocal/share 0755 root root -
d /var/usrlocal/src 0755 root root -
d /var/tmp 1777 root root -
EOF
# Preserve additional top-level /var directories created by packages.
extra_conf="$ROOTFS/usr/lib/tmpfiles.d/bootc-var-ext.conf"
rm -f -- "$extra_conf"
for path in "$ROOTFS/var"/*; do
    [[ -d "$path" && ! -L "$path" ]] || continue
    relative=${path#"$ROOTFS/"}
    case "$relative" in
        var/home|var/roothome|var/lib|var/opt|var/srv|var/mnt|var/usrlocal|var/tmp)
            continue ;;
    esac
    mode=$(stat -c '%a' "$path")
    printf 'd /%s %s root root -\n' "$relative" "$mode" >> "$extra_conf"
done
ensure_link "$ROOTFS/var/run" ../run
remove_path "$ROOTFS/usr/lib/tmpfiles.d/home.conf"

# provision.conf: point /root entries at /var/roothome, and drop any
# redundant `d- /var/roothome` line (basic-fixes.yaml).
provision="$ROOTFS/usr/lib/tmpfiles.d/provision.conf"
if [[ -f "$provision" ]]; then
    sed -E \
        -e 's#^([[:space:]]*[^[:space:]]+[[:space:]]+)/root(/[^[:space:]]*)?([[:space:]].*)?$#\1/var/roothome\2\3#' \
        -e '/^d-[[:space:]]+\/var\/roothome[[:space:]]/d' \
        "$provision" > "$provision.tmp"
    mv -- "$provision.tmp" "$provision"
fi

printf 'Relocating RPM database to /usr/share/rpm\n'
mkdir -p -- "$ROOTFS/usr/share/rpm"
rpmdb_src=''
for candidate in "$ROOTFS/usr/lib/sysimage/rpm" "$ROOTFS/var/lib/rpm"; do
    if [[ -d "$candidate" && ! -L "$candidate" ]]; then
        for f in "$candidate"/*; do
            [[ -e "$f" || -L "$f" ]] || continue
            case "$f" in
                *.sqlite|*.db) rpmdb_src=$candidate; break ;;
            esac
        done
        [[ -n "$rpmdb_src" ]] && break
    fi
done
if [[ -n "$rpmdb_src" ]]; then
    cp -a -- "$rpmdb_src"/. "$ROOTFS/usr/share/rpm/"
    remove_path "$rpmdb_src"
fi
ensure_link "$ROOTFS/var/lib/rpm" ../../usr/share/rpm
mkdir -p -- "$ROOTFS/usr/lib/rpm/macros.d"
printf '%%_dbpath /usr/share/rpm\n' > "$ROOTFS/usr/lib/rpm/macros.d/macros.rpm-ostree"

printf 'Writing bootc configuration\n'
mkdir -p -- "$ROOTFS/usr/lib/ostree" "$ROOTFS/usr/lib/kernel/install.conf.d"
cat > "$ROOTFS/usr/lib/ostree/prepare-root.conf" <<'EOF'
[composefs]
enabled = true

[sysroot]
readonly = true
EOF
printf 'layout=ostree\n' > "$ROOTFS/usr/lib/kernel/install.conf"
printf 'layout=ostree\n' > "$ROOTFS/usr/lib/kernel/install.conf.d/00-bootc-kernel-layout.conf"

printf 'Writing dracut configuration\n'
mkdir -p -- "$ROOTFS/usr/lib/dracut/dracut.conf.d"
cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/10-bootc-base.conf" <<'EOF'
# Generated by imagectl
hostonly=no
export DRACUT_NO_XATTR=1
add_dracutmodules+=" kernel-modules dracut-systemd systemd-initrd base ostree bootc "
EOF
cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/59-altfiles.conf" <<'EOF'
# Generated by imagectl
install_items+=" /usr/lib/passwd /usr/lib/group "
EOF
cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/22-bootc-generic.conf" <<'EOF'
# Generated by imagectl
add_dracutmodules+=" virtiofs "
EOF
if [[ -d "$ROOTFS/usr/lib/dracut/modules.d/97tpm2-tss" ]]; then
    cat > "$ROOTFS/usr/lib/dracut/dracut.conf.d/49-bootc-tpm2-tss.conf" <<'EOF'
# Generated by imagectl
add_dracutmodules+=" tpm2-tss "
EOF
fi

printf 'Writing dnf configuration\n'
if [[ -d "$ROOTFS/usr/share/dnf5/libdnf.conf.d" ]]; then
    cat > "$ROOTFS/usr/share/dnf5/libdnf.conf.d/20-ostree-installonlypkgs.conf" <<'EOF'
[main]
installonlypkgs=''
EOF
    cat > "$ROOTFS/usr/share/dnf5/libdnf.conf.d/20-ostree-protect_running_kernel.conf" <<'EOF'
[main]
protect_running_kernel=False
EOF
else
    dnf4_conf="$ROOTFS/etc/dnf/dnf.conf"
    mkdir -p -- "$ROOTFS/etc/dnf"
    grep -q "^installonlypkgs=''" "$dnf4_conf" 2>/dev/null || printf "installonlypkgs=''\n" >> "$dnf4_conf"
    grep -q '^protect_running_kernel=False' "$dnf4_conf" 2>/dev/null || printf 'protect_running_kernel=False\n' >> "$dnf4_conf"
fi

if [[ -f "$ROOTFS/etc/passwd" ]]; then
    mkdir -p -- "$ROOTFS/usr/lib"
    cp -a -- "$ROOTFS/etc/passwd" "$ROOTFS/usr/lib/passwd"
fi
if [[ -f "$ROOTFS/etc/group" ]]; then
    # Copy the full group file to the immutable layer. (rpm-ostree's
    # postprocess-conf `etc-group-members` would additionally split wheel,
    # systemd-journal, tss, kvm, adm into /etc/group; the dnf --installroot
    # path keeps the whole file immutable instead.)
    mkdir -p -- "$ROOTFS/usr/lib"
    cp -a -- "$ROOTFS/etc/group" "$ROOTFS/usr/lib/group"
fi

printf 'Writing systemd configuration\n'
mkdir -p -- "$ROOTFS/usr/lib/systemd/system/local-fs.target.wants" "$ROOTFS/usr/lib/systemd/system-preset"
ensure_link "$ROOTFS/usr/lib/systemd/system/local-fs.target.wants/tmp.mount" ../tmp.mount
cat > "$ROOTFS/usr/lib/systemd/system-preset/85-bootc.preset" <<'EOF'
# Generated by imagectl
disable dnf-makecache.timer
EOF
cat > "$ROOTFS/usr/lib/systemd/system-preset/85-bootc-bootloader-update.preset" <<'EOF'
enable bootloader-update.service
EOF
mkdir -p -- "$ROOTFS/etc"
: > "$ROOTFS/etc/machine-id"

run_chroot() { chroot "$ROOTFS" "$@"; }

if (( ! skip_chroot )) && [[ -d "$ROOTFS/usr/lib/modules" ]]; then
    (( EUID == 0 )) || die 'chroot operations require root; use --skip-chroot'
    kernel_dir=''
    for candidate in "$ROOTFS/usr/lib/modules"/*; do
        [[ -d "$candidate" ]] && { kernel_dir=$candidate; break; }
    done
    if [[ -n "$kernel_dir" ]]; then
        kver=${kernel_dir##*/}
        root_path="$ROOTFS/root"
        root_was_symlink=0
        if [[ -L "$root_path" ]]; then
            root_was_symlink=1
            remove_path "$root_path"
            mkdir -p -- "$root_path"
        fi
        mounted=()
        cleanup_chroot() {
            for (( i=${#mounted[@]}-1; i>=0; i-- )); do
                umount -R -- "${mounted[i]}" 2>/dev/null || true
            done
            if (( root_was_symlink )); then
                remove_path "$root_path"
                ln -s -- var/roothome "$root_path"
            fi
        }
        trap cleanup_chroot EXIT
        for systemd_dir in etc/systemd/system etc/systemd/user; do
            remove_path "$ROOTFS/$systemd_dir"
            mkdir -p -- "$ROOTFS/$systemd_dir"
        done
        for mountpoint in proc sys dev; do mkdir -p -- "$ROOTFS/$mountpoint"; done
        mount -t proc proc "$ROOTFS/proc"; mounted+=("$ROOTFS/proc")
        mount -t sysfs sys "$ROOTFS/sys"; mounted+=("$ROOTFS/sys")
        mount --rbind /dev "$ROOTFS/dev"; mounted+=("$ROOTFS/dev")
        run_chroot depmod "$kver"
        run_chroot dracut --no-hostonly --kver "$kver" --force "/usr/lib/modules/$kver/initramfs.img"
        run_chroot systemctl preset-all
        run_chroot systemctl --user --global preset-all
        cleanup_chroot
        trap - EXIT
    fi
fi

printf 'Generating bootupd metadata\n'
bootupctl="$ROOTFS/usr/bin/bootupctl"
if [[ -x "$bootupctl" ]]; then
    updates="$ROOTFS/usr/lib/bootupd/updates"
    mkdir -p -- "$updates"
    timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    rpm_evr() {
        (( skip_chroot )) && return 0
        chroot "$ROOTFS" rpm -q --qf '%{EVR}' "$1" 2>/dev/null || true
    }
    efi_source="$ROOTFS/boot/efi/EFI"
    if [[ -d "$efi_source" ]]; then
        arch=$(uname -m)
        case "$arch" in
            aarch64) grub_package=grub2-efi-aa64; shim_package=shim-aa64 ;;
            *) grub_package=grub2-efi-x64; shim_package=shim-x64 ;;
        esac
        remove_path "$updates/EFI"
        cp -a -- "$efi_source" "$updates/EFI"
        grub_version=$(rpm_evr "$grub_package")
        shim_version=$(rpm_evr "$shim_package")
        version_parts=()
        versions=()
        if [[ -n "$grub_version" ]]; then
            version_parts+=("$grub_package-$grub_version")
            versions+=("{\"name\": \"grub2\", \"rpm_evr\": \"$grub_version\"}")
        fi
        if [[ -n "$shim_version" ]]; then
            version_parts+=("$shim_package-$shim_version")
            versions+=("{\"name\": \"shim\", \"rpm_evr\": \"$shim_version\"}")
        fi
        version_csv=$(IFS=,; printf '%s' "${version_parts[*]}")
        versions_json=$(IFS=,; printf '%s' "${versions[*]}")
        printf '{\n  "timestamp": "%s",\n  "version": "%s",\n  "versions": [%s]\n}\n' \
            "$timestamp" "$version_csv" "$versions_json" > "$updates/EFI.json"
    fi

    # BIOS metadata (mirrors bootupctl generating BIOS.json when the full
    # BIOS chain — grub2-install + i386-pc modules — is present).
    if [[ -e "$ROOTFS/usr/sbin/grub2-install" && -d "$ROOTFS/usr/lib/grub/i386-pc" ]]; then
        grub2_ver=$(rpm_evr grub2-tools)
        if [[ -n "$grub2_ver" ]]; then
            printf '{\n  "timestamp": "%s",\n  "version": "grub2-tools-%s",\n  "versions": [\n    {\n      "name": "grub2",\n      "rpm_evr": "%s"\n    }\n  ]\n}\n' \
                "$timestamp" "$grub2_ver" "$grub2_ver" > "$updates/BIOS.json"
        fi
    fi
fi

printf 'Relocating boot files\n'
mkdir -p -- "$ROOTFS/usr/lib/ostree-boot"
if [[ -d "$ROOTFS/boot" ]]; then
    for entry in "$ROOTFS/boot"/*; do
        [[ -e "$entry" || -L "$entry" ]] || continue
        cp -a -- "$entry" "$ROOTFS/usr/lib/ostree-boot/"
        remove_path "$entry"
    done
fi
mkdir -p -- "$ROOTFS/boot"
# bootupctl's update-metadata generator + RHEL-78104 workaround removes the
# loader dir from the immutable payload; do the same here.
remove_path "$ROOTFS/usr/lib/ostree-boot/loader"

printf 'Copying up SELinux policy\n'
# selinux-copyup.sh: force copy-up of /etc/selinux/targeted so libsemanage's
# atomic renames succeed on overlayfs (tuna-os/tunaOS#1562).
targeted="$ROOTFS/etc/selinux/targeted"
if [[ -d "$targeted" ]]; then
    rm -rf -- "$targeted/tmp" "$targeted/previous"
    cp -a -- "$targeted" "$targeted.copyup"
    rm -rf -- "$targeted"
    mv -- "$targeted.copyup" "$targeted"
fi

printf 'Cleaning transient files\n'
for directory in var/cache var/tmp var/log run tmp; do
    [[ -d "$ROOTFS/$directory" ]] && rm -rf -- "${ROOTFS:?}/$directory"/*
done
remove_path "$ROOTFS/usr/share/rpm/rpmdb.sqlite-wal"
remove_path "$ROOTFS/usr/share/rpm/rpmdb.sqlite-shm"

printf 'Rootfs finalized: %s\n' "$ROOTFS"