name: Build base image

on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile.base'
      - '.github/workflows/build-base.yml'

  schedule:
    - cron: "21 0 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  build:

    uses: ./.github/workflows/bootable-containers.yml

    with:

      containerfile: Containerfile.base

      image_tag: base

      image_title: Asahi Remix Atomic Base

      image_description: Asahi Remix Base Image

    secrets:
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
